### ISSUE TITLE
Can't create openstack deployment

### ISSUE THREAD

**Issue by jseaidou** [oneops/OneOps#10]
I have created a openstack cloud following these instructions: http://oneops.github.io/user/howto/#add-a-new-cloud however when it comes to enabling the platform for deployment I get the error message that I am missing the service: 
dns, gdns. 
The documentation isn't very clear on this or even where I can set these settings.

**Comment by jseaidou** [comment]
Apparently the error only appears when trying to enable via the "3 dots" beside the platform, if enabling via the "_action_" button it succeeds but fails on deployment due to sshkeys.

**Comment by ighouri** [comment]
@jseaidou ,
Please update chef-logs here and the failure that you are getting on sshkeys step.

**Comment by mosabua** [comment]
Please reopen with more details if required.
