### ISSUE TITLE
Deploying failed due to sshkeys

### ISSUE THREAD

**Issue by jseaidou** [oneops/OneOps#13]
For any platform I create for the Openstack cloud, I am getting failed deployments at the sshKeys component level (step 1 in the deployment plan). 
I can't modify the component to add any ssh keys, and pressing repair (as the admin) gives me unauthorized access.
Here is the error output I see from the deployment plan logs

```
[2016-03-30T02:10:06+00:00] ERROR: no implicit conversion of nil into String
[2016-03-30T02:10:06+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
[2016-03-30T02:18:17+00:00] FATAL: Stacktrace dumped to /tmp/chef-stacktrace.out
[2016-03-30T02:18:17+00:00] ERROR: Running exception handlers
[2016-03-30T02:18:17+00:00] ERROR: Exception handlers complete
```

**Comment by gauravlall** [comment]
@jseaidou  How are you deploying the instance using vagrant or AWS ?  
fyi @sleepyorion

**Comment by wbentley15** [comment]
Any traction on this issue?  I am facing the same problem and would love some help.

**Comment by RachitBahadur** [comment]
I am also finding the same issue. The instance is being deployed using AWS.
Kindly advise!

**Comment by chichimedina** [comment]
Hey guys, I'm facing the exact same issue: I installed vagrant-version of OneOps and everything goes fine. As soon as I go to deploy, the sshkeys component fails stating that "an unspecified fault" has occurred.

I cannot modify this sshkey component nor take it out of the deployment list.

This happens either either an medium-advanced design (multiple servers, and components) or with the most basic design (just one platform and its default components).

By looking at the logs, there're a bunch of Chef fatal errors when runs in background. Most of them related to "Nil".

Does anyone have a clue of this issue?

**Comment by mosabua** [comment]
Is this still a problem?

**Comment by wbentley15** [comment]
Not sure as I moved on to other projects.  Moving into a new role soon and plan to try it again.  Will let you know.


Walter

"Just cause we're magic, doesn't mean we are not real..."

**Comment by mosabua** [comment]
Closing for now. Please file a new issue with more details if you encounter the problem again.

**Comment by Reddyvedanth** [comment]
failed without any specified faults error facing  when  i click on commit and deploy
