### ISSUE TITLE
Regarding OneOps API Documentation

### ISSUE THREAD

**Issue by ahsan518** [oneops/OneOps#14]
Hi,

This is not a bug.

I was going through the API Documentation and wasn't able to clearly understand how the API works in OneOps. Basically the complete workflow of how oneops API works.

Need help in this regard.

Thanks

**Comment by mosabua** [comment]
The API does not have a workflow. It is just a REST API with numerous endpoints. Please check out the documentation at http://oneops.com/developer/integration-development/index.html
