### ISSUE TITLE
Installation through vagrant on MacOSX - SSH keys issue

### ISSUE THREAD

**Issue by brountreeRS** [oneops/OneOps#16]
Here is the output from the terminal:

brians-MacBook-Pro:vagrant-centos7 brianrountree$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'box-cutter/centos72'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'box-cutter/centos72' is up to date...
==> default: Setting the name of the VM: oneops
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 3001 (guest) => 3003 (host) (adapter 1)
    default: 3000 (guest) => 9090 (host) (adapter 1)
    default: 8161 (guest) => 8166 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

**Comment by nimkar** [comment]
What version of Vagrant are you using ?

**Comment by nimkar** [comment]
It seems this is due to a known Vagrant bug in the release 1.8.5. More information and fix are here.
https://github.com/mitchellh/vagrant/issues/7610
Short version is
1) You can apply the patch mentioned in the URL above.
2) You can downgrade to 1.8.4
3) You can wait for 1.8.6 in which the fix will be rolled up (not really a option, install will be broken till then).

**Comment by mosabua** [comment]
Is this still a problem for you @nimkar ?

**Comment by nimkar** [comment]
@mosabua Nope. Just upgraded my infrastructure yesterday (Vagrant, VirtualBox etc.) and did a build and everything works.

**Comment by mosabua** [comment]
Great. Thanks @nimkar
