### ISSUE TITLE
How can I generate oneops-continuous.tar.gz file in oneops-setup.sh

### ISSUE THREAD

**Issue by yrmallu** [oneops/oneops#25]
mv: cannot stat ‘/tmp/oneops-continuous.tar.gz’: No such file or directory
tar (child): oneops-continuous.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
doing git pull on dev-tools
Already up-to-date.
Starting at : 12:22:06
Stopping services to free up memory for build
Stopping cassandra (via systemctl):                        [  OK  ]
Skipping artifact build
Completed git build : 12:22:14
Starting services after build before deploy
Starting cassandra (via systemctl):                        [  OK  ]
Initializing DB..
/home/oneops/init_db.sh: line 5: cd: /home/oneops/dist: No such file or directory
tar (child): db.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by mosabua** [comment]
I am not sure what the context of this question is. With this information only we can not provide any answer.
