### ISSUE TITLE
The OneOps preconf AMIs are Unusable Due to Database Errors

### ISSUE THREAD

**Issue by tobrien** [oneops/oneops#28]
When you attempt to use the AMIs for OneOps your instance will start up and you will be able to login with the test user oneops/oneops, but after that the system is unusable due to some issue with the database.

The first operation I tried was the change the email of an organization owner.  When I tried this I was greeted with a Postgresql error message.

Then, one of the first steps the documentation directs you to is to update your AWS keys in the cloud.  When you attempt to do this you are met with the error message:

`### Error updating database. Cause: org.postgresql.util.PSQLException: ERROR: Date out of range. Fix the cm_ci_attribute_log_insert() function! Where: SQL statement "insert into cm_ci_attribute_log(log_id, log_time, log_event, ci_id, ci_attribute_id, attribute_id, attribute_name, comments, owne ...
`
![image](https://user-images.githubusercontent.com/36787/27920318-c5a547a0-6239-11e7-8794-2d04069b86df.png)

**Comment by mosabua** [comment]
https://jira.walmart.com/browse/PLONEOPS-14987

**Comment by mosabua** [comment]
We have to rejig the whole installation instructions. Removing docker and ami and more. Also need to test setup repo or alternatively need to build from source.

**Comment by tobrien** [comment]
Closing - we've temporarily removed the AMI instructions while we alter the installation process.
