### ISSUE TITLE
OneOps Setup Failing Due to Change in Date

### ISSUE THREAD

**Issue by maham-nazir-confiz** [oneops/oneops#297]
Since yesterday, I am unable to create any new environment on OneOps. Every time I try I get the following error.

#### Error updating database. Cause: org.postgresql.util.PSQLException: ERROR: Date out of range. Fix the cm_ci_log_insert() function! Where: SQL statement "insert into cm_ci_log(log_id, log_time, log_event, ci_id, ci_name, class_id, class_name, comments, ci_state_id, ci_state_id_old, created_by ...

Also when I try to redeploy an old environment I get the following error
#### Failed. Response code = 500. Response message = Internal Server Error.

When I try to commit a design, it doesn't commit at all. Changes made are not saved.

When I moved the date back to `December 31, 2017` the setup began working again. Please have a look at what's wrong.
Thank you.

**Comment by yrmallu** [comment]
@maham-nazir-confiz How you fixed this?

**Comment by maham-nazir-confiz** [comment]
@yrmallu 
I didn't. The issue was fixed by the repo owners.
