### ISSUE TITLE
Feedback & Support contact

### ISSUE THREAD

**Issue by madhuakula** [oneops/OneOps#3]
We have to create a contact information for feedback (or) issues, Other than slack.

**Comment by nimkar** [comment]
I agree. Can it be github centric so people from github can also participate in issue raising and resolution ?

**Comment by madhuakula** [comment]
Yes, That's true. I completely agree with you @nimkar . I am thinking in sensitive information discussion and disclosures. Anyway I think they are working on this. You can close this issue and make it as feature request.

Thanks

**Comment by jorgevgut** [comment]
Hi, could you please consider IRC? I have been looking for an easy place to ask for questions :)
Cheers

**Comment by mosabua** [comment]
For the moment we are sticking to slack for real time interactions. All our developers and support staff are on there. In addition we do now monitor and update issues here (and other repos including the website and such).
