### ISSUE TITLE
Provide Instructions and Automation for Connecting OneOps to AWS

### ISSUE THREAD

**Issue by tobrien** [oneops/oneops#30]
If I stand-up a OneOps instance locally and I want to create Clouds that point to AWS EC2, EBS, ELB, and other AWS resources there is no instructions for doing this with the system as configured.   I'm not sure what packs to install or even where to begin.

We need to document the process of getting your OneOps installation updated with the necessary circuit to connect to AWS.   Ideally you would be able to run a script that would automate the installation of the necessary components, and this script would also be able to quickly configure some clouds to get a user started.

**Comment by rgtripathi** [comment]
Yes, I too am looking to stand up a local instance and trigger instances in AWS/Azure but cannot locate any clear instructions/docs around how to do this. Any help appreciated !
