### ISSUE TITLE
distribution-18.01.03-6-SNAPSHOT-oneops.tar.gz does not exist

### ISSUE THREAD

**Issue by VVduke** [oneops/oneops#300]
mvn clean install build failure caused by " java.lang.RuntimeException /oneops/oneops-distribution/target/distribution-18.01.03-6-SNAPSHOT-oneops.tar.gz does not exist"

**Comment by VVduke** [comment]
@walmartlabs-cla-admin

**Comment by VVduke** [comment]
Is there anyone help me to solve this problem @jvanzyl

**Comment by technicsntricks** [comment]
Hi, I am also facing the same issue can any one help me on this.

**Comment by aravicamp** [comment]
Hi, I am also stumped on the same issue.  Looks like the 0-oneops assembly is not creating the archive. Any pointers would be helpful.

[ERROR] Failed to execute goal io.takari.maven.plugins:provisio-maven-plugin:0.1.50:provision (default-provision) on project distribution: Error provisioning assembly.: The specified file /opt/oneops/oneops-distribution/target/distribution-18.01.03-14-SNAPSHOT-oneops.tar.gz does not exist.

**Comment by billheck** [comment]
Sounds like the same issue for me as well:  

[ERROR] Failed to execute goal io.takari.maven.plugins:provisio-maven-plugin:0.1.50:provision (default-provision) on project distribution: Error provisioning assembly.: The specified file /home/ubuntu/oneops/oneops-distribution/target/distribution-18.01.15-7-SNAPSHOT-oneops.tar.gz does not exist. -> [Help 1]

**Comment by gauravlall** [comment]
maybe try deleting 1.xml locally and see if that works .

**Comment by abhitekula** [comment]
Try in the oneops/oneops-distribution/target/ directory.
tar -zcvf distribution-18.01.15-7-SNAPSHOT-oneops.tar.gz distribution-18.01.15-7-SNAPSHOT-archive/

And replace the 18.01.15-7 with whatever version it is.

**Comment by xevelzol** [comment]
> Try in the oneops/oneops-distribution/target/ directory.
tar -zcvf distribution-18.01.15-7-SNAPSHOT-oneops.tar.gz distribution-18.01.15-7-SNAPSHOT-archive/

> And replace the 18.01.15-7 with whatever version it is.

then run maven without "clean", like this:
mvn install
