### ISSUE TITLE
Missing program "bundle" in Display

### ISSUE THREAD

**Issue by CodeAayu** [oneops/oneops#495]
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (default) on project display: Command execution failed.: Cannot run program "bundle" (in directory "/path/to/oneops/display"): error=2, No such file or directory -> [Help 1]

Build failed at Display

**Comment by CodeAayu** [comment]
Installing using this command.
mvn install -Dmaven.test.skip=true -Pvagrant

**Comment by xevelzol** [comment]
use this:
gem install bundler
