### ISSUE TITLE
Idea: why we are not supporting the https://jclouds.apache.org/

### ISSUE THREAD

**Issue by rbhawsar** [oneops/oneops#508]
Hi Team,
we are using oneops and I came to know that we are not supporting the jclouds.  if I am wrong please correct me.
If we are not supporting jclouds, can we support jclouds I would be interested to help here.
I am just a user of oneops at walmart but would be glad to to contribute in onops.

please provide your input on supporting apace jclouds.
Thanks and Regards,
Rahul

**Comment by mosabua** [comment]
We are not interested in adding jclouds to the mix.
