### ISSUE TITLE
Is this repo maintained?

### ISSUE THREAD

**Issue by MmtBkn** [oneops/oneops#518]
Hello @,

Looks like no updates made for long time, and I don't see comments on issues. 

I followed the installation guide and wasn't able to run the app. Do you guys are planning to keep maintain it? Other wise, that would be nice if you can add notification to website and archive the repo? 

Thanks.

**Comment by sleepyorion** [comment]
@MmtBkn - Although I don't work on this project anymore but if you give more details maybe I offer you advices on how to proceed.  I was able to setup a working instance of OneOps few months ago.
