### ISSUE TITLE
OneOps sync packs exception

### ISSUE THREAD

**Issue by bilal-naeem-confiz** [oneops/oneops#59]
After installing OneOps on a vagrant machine I ran into some issues. First, there were **no cloud locations**. I fixed that by running the command `circuit clouds`. The next issue that I am facing is that there are **only 2 packs** showing when building a platform. I tried to fix this issue in a similar way by running the command `circuit packs` but it throws an error.
```
============> Platform
Creating resource ansible for ansible
ERROR: knife encountered an unexpected error
This may be a bug in the 'pack sync' knife command or plugin
Please collect the output of this command with the -VV option before filing a bug report.
Exception: NoMethodError: undefined method `comments=' for false:FalseClass
fail. knife pack sync -a returned: 100
```

How can I resolve this error

**Comment by fgarat-nexa** [comment]
Hi, try removing the ansible pack and retry the command circuit packs
