### ISSUE TITLE
can not install Jenkins, exiting :-(

### ISSUE THREAD

**Issue by ahsan519** [oneops/OneOps#6]
Hi,

I have been having this problem whenever i try to install oneops with Vagrant, need help:

==> default: Downloading jenkins war: http://mirror.xmission.com/jenkins/war-stable/1.642.1/jenkins.war
==> default: Can not instal jenkins, exiting :-(

![screenshot from 2016-02-08 21 06 27](https://cloud.githubusercontent.com/assets/17133024/12906808/73debeda-cea9-11e5-9286-81d44cf8a88e.png)

**Comment by gauravlall** [comment]
Hi Seeing that you are trying in Ubuntu , Could you please check if this is related to this https://github.com/oneops/setup/pull/8 ?

**Comment by kfilipovski** [comment]
per slack this is resolved
