### ISSUE TITLE
Integrations more cloud providers

### ISSUE THREAD

**Issue by sjkeerthi** [oneops/OneOps#8]
Hi All,

I hope if we add cloudstack / Docker management / Digital Ocean / Softlayer will be great in the upcoming OneOps

**Comment by mosabua** [comment]
Those are all on the wishlist but will need to be tracked and implemented by community members.

**Comment by mosabua** [comment]
We would have to submit as separate issues if anything is actually moving forwards with any of these providers. If you have a specific need and are willing to work with us to move it forward please contact us.

**Comment by nimkar** [comment]
Just an FYI. I have a fork for DigitialOcean in progress. I can create Droplets successfully but the code needs a bit polishing. Will submit a PR soon. Let me know if anyone wants to team up for other clouds.

**Comment by mosabua** [comment]
Sounds great .. I look forward to hear from you soon @nimkar
