### ISSUE TITLE
should the setup scripts from dev-tools repo be merged into this repo?

### ISSUE THREAD

**Issue by rameshjanjyam** [oneops/oneops#88]
During oneops build [oneops-setup.sh script](https://github.com/oneops/oneops/blob/master/oneops-packer/script/oneops/oneops-setup.sh) copies setup scripts from `dev-tools` repo. The scripts uses this repo url https://github.com/oneops/dev-tools which gets redirected to https://github.com/oneops-archive/dev-tools. It is redirecting to `oneops-archive` repo. should these setup scripts be added to [main oneops repo](https://github.com/oneops/oneops)

**Comment by sleepyorion** [comment]
@rameshjanjyam : we are going to refactor the setup in the future with ansible playbook so let's stay put on that for now.

**Comment by rameshjanjyam** [comment]
ok @sleepyorion
