### ISSUE TITLE
OneOps Installation on Centos 7

### ISSUE THREAD

**Issue by ahsan519** [oneops/OneOps#9]
Hi,

I am actually trying to install OneOps installation on Centos 7 bypassing vagrant. So the steps which I followed was after cloning the setup from vagrant-centos7. 
After the installation, I executed oo-setup.sh but it gets stuck at waiting for jenkins to come online.

Need some help.

**Comment by nimkar** [comment]
@ahsan519 were you able to make any progress  or are you still stuck ?

**Comment by mosabua** [comment]
Please reopen with more details if required.

**Comment by yrmallu** [comment]
May 10, 2017 10:36:08 AM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'oneOpsConfig': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.core.env.Environment com.oneops.config.OneOpsConfig.env; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [com.oneops.sensor.listeners.BasicListener] for bean with name 'basicListener' defined in ServletContext resource [/WEB-INF/application-context.xml]: problem with class file or dependent class; nested exception is java.lang.NoClassDefFoundError: com/espertech/    /client/UpdateListener
Related cause: org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [com.oneops.sensor.listeners.BasicListener] for bean with name 'basicListener' defined in ServletContext resource [/WEB-INF/application-context.xml]: problem with class file or dependent class; nested exception is java.lang.NoClassDefFoundError: com/espertech/esper/client/UpdateListener
Related cause: org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [com.oneops.sensor.listeners.OpsEventListener] for bean with name 'opsEventListener' defined in ServletContext resource [/WEB-INF/application-context.xml]: problem with class file or dependent class; nested exception is java.lang.NoClassDefFoundError: com/espertech/esper/client/UpdateListener
Related cause: org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [com.oneops.sensor.listeners.CloseEventListener] for bean with name 'closeEventListener' defined in ServletContext resource [/WEB-INF/application-context.xml]: problem with class file or dependent class; nested exception is java.lang.NoClassDefFoundError: com/espertech/esper/client/UpdateListener
Related cause: org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [com.oneops.sensor.listeners.ChannelDownListener] for bean with name 'channelDownListener' defined in ServletContext resource [/WEB-INF/application-context.xml]: problem with class file or dependent class; nested exception is java.lang.NoClassDefFoundError: com/espertech/esper/client/UpdateListener
